#include <stdlib.h>
#include <stdio.h>
#include "data_structures/priority_queue.h"

/*
Set my starting point as a binary heap implementation of a priority queue generated by ChatGPT
Prompt = "Implement a priority queue in C"

I then modified this implementation to fit my use case, specifically with the abstraction of data types
*/

void swap_pointers(void** a, int** b) {
    void* temp = *a;
    *a = *b;
    *b = temp;
}

PriorityQueue* create_priority_queue(int capacity, int (*compare)(void*, void*)) {
    PriorityQueue* priority_queue = (PriorityQueue*) malloc(sizeof(PriorityQueue));
    priority_queue->array = (void**) malloc(sizeof(void*) * capacity);
    priority_queue->size = 0;
    priority_queue->capacity = capacity;
    priority_queue->compare = compare;
    return priority_queue;
}

bool is_empty(PriorityQueue* pq) {
    return pq->size == 0;
}

void push(PriorityQueue* pq, void* item) {
    if (pq->size >= pq->capacity) {
        pq->capacity *= 2;
        pq->array = realloc(pq->array, sizeof(void*) * pq->capacity);
    }

    pq->array[pq->size++] = item;

    int current_index = pq->size;
    //Bubble up
    while (current_index > 0 && pq->array[current_index] > pq->array[(current_index-1)/2]) {
        swap_pointers(pq->array[current_index], pq->array[(current_index-1)/2]);
        current_index = (current_index-1)/2;
    }
}

void* pop(PriorityQueue* pq) {
    if (is_empty(pq)) return NULL;

    void* result = pq->array[0];
    pq->array[0] = pq->array[--pq->size];

    int current = 0;
    while (current * 2 + 1 < pq->size) {
        int child;
        if (current * 2 + 2 == pq->size) {
            child = current * 2 + 1;
        } else {
            child = pq->array[current * 2 + 1] > pq->array[current * 2 + 2] ? current * 2 + 1 : current * 2 + 2;
        }

        if (pq->array[current] >= pq->array[child]) {
            break;
        }

        swap_pointers(pq->array[current], pq->array[child]);
        current = child;
    }

    return result;
}

void free_priority_queue(PriorityQueue* pq) {
    free(pq->array);
    free(pq);
}